package edu.yu.velocitytrading.model;

import java.io.Serializable;
import java.util.UUID;

/**
 * Authoritative net quantity held for a symbol.
 * Object to hold position generated by the Trading State Service.
 * A position is updated by applying recorded fills.
 * @param symbol ticker
 * @param netQuantity positive for long, negative for short
 * @param version monotonic per symbol
 * @param lastFillId
 */
public record Position(String symbol, int netQuantity, long version, UUID lastFillId) implements Identifiable<String>, Serializable {

    @Override
    public String getId() {
        return symbol;
    }
}
